apiVersion: v1
kind: Service
metadata:
  name: {{ include "course-app.fullname" . }}-service
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.port }}
  selector:
    app: {{ include "course-app.fullname" . }}
