apiVersion: v1
kind: Service
metadata:
  name: {{ include "course-app.fullname" . }}-redis
spec:
  type: ClusterIP
  selector:
    app: {{ include "course-app.fullname" . }}-redis
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}