apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "course-app.fullname" . }}-redis
spec:
  serviceName: {{ include "course-app.fullname" . }}-redis
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "course-app.fullname" . }}-redis
  template:
    metadata:
      labels:
        app: {{ include "course-app.fullname" . }}-redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          ports:
            - containerPort: {{ .Values.redis.service.port }}
          volumeMounts:
            - name: redis-data
              mountPath: /data

  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.redis.storage.size }}